---
# AWS IAM MCP Server Integration Tests for run_tool action plugin
# Testing IAM operations against AWS IAM API

# - /mcp/job_management
# - /mcp/inventory_management
# - /mcp/system_monitoring
# - /mcp/user_management
# - /mcp/security_compliance
# - /mcp/platform_configuration

- name: MCP Ansible
  hosts: ec2-54-165-75-147.compute-1.amazonaws.com
  #hosts: localhost
  connection: ansible.mcp.mcp
  vars:
    ansible_mcp_server_name: ec2-54-165-75-147.compute-1.amazonaws.com:8448
    #ansible_mcp_server_name: https://ec2-54-165-75-147.compute-1.amazonaws.com:8448
    ansible_mcp_validate_certs: false
    ansible_mcp_bearer_token: "{{ ansible_ssh_pass }}"
  environment:
        MCP_BEARER_TOKEN: "{{ ansible_ssh_pass }}"
  tasks:
    # - name: Retrieve list of supported tools from an MCP server
    #   ansible.mcp.tools_info:

    # - name: Retrieve server info from GitHub MCP server
    #   ansible.mcp.server_info:

    # - name: List Jobs
    #   ansible.mcp.run_tool:
    #     #name: list_jobs
    #     name: job_management
    #     args:
    #     max_items: 10
    #   no_log: false
    #   register: jobs_list

